#!/usr/bin/env bash

########################################
#########Kristina Gagalova##############
############Mar 21 2017#################
########################################

# Description: given a fasta file with Kollector seed sequences, Kollector output against it
# BLAST documentation: https://www.ncbi.nlm.nih.gov/books/NBK279675/

#############################################################
#------------------------------------------------------------
#blast program version
BLAST=/home/shammond/src/ncbi-blast-2.2.31+/bin

#seq and seed file that need to be blasted
SEQ=/projects/spruceup/pglauca/WS77111/assemblies/kollector/EvalSuccessRate/assembledtargets_half1000_1.fa
SEED=/projects/spruceup/pglauca/WS77111/assemblies/kollector/EvalSuccessRate/seed1000/cdhit-output-4_1.fasta

#out names
BASE_OUT=/projects/spruceup/pglauca/WS77111/assemblies/kollector/EvalSuccessRate/Half1000_1
OUT_DB=Half1000_1
BLAST_OUT=$OUT_DB.allvsseed.tsv

##############################################################
#     Program here
##############################################################

#-------------------------------------------------------------
#create DB: SEED
#-------------------------------------------------------------
mkdir -p $BASE_OUT
cd $BASE_OUT
$BLAST/makeblastdb -in $SEED -dbtype nucl -out $OUT_DB

#-------------------------------------------------------------
#blast SEQ sequences with BLASTN
#-------------------------------------------------------------

$BLAST/blastn -db $OUT_DB -query $SEQ -outfmt '6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovs qcovhsp' -out seq.${BLAST_OUT} -num_threads 4
awk '$3 > 90 && $13 > 90' seq.${BLAST_OUT} > out.seq.${BLAST_OUT}

#-------------------------------------------------------------
#create DB: SEQ
#-------------------------------------------------------------
$BLAST/makeblastdb -in $SEQ -dbtype nucl -out $OUT_DB

#-------------------------------------------------------------
#blast SEED sequenc with BLASTN
#-------------------------------------------------------------

$BLAST/blastn -db $OUT_DB -query $SEED -outfmt '6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovs qcovhsp' -out seed.${BLAST_OUT} -num_threads 4
awk '$3 > 90 && $13 > 90' seed.${BLAST_OUT} > out.seed.${BLAST_OUT}

rm *.nhr *.nin *.nsq
